Repository influxdata/influxdb-client-java, pull requests merged in 2020-06, with the labels that each got.

#120 Instant.now() return is MilliSeconds
  README.md
Labels: documentation

#122 feat: Removed log system from Bucket, Dashboard, Organization, Task and Users API
  CHANGELOG.md
  client/src/generated/java/com/influxdb/client/domain/BucketLinks.java
  client/src/generated/java/com/influxdb/client/domain/CloudUser.java
  client/src/generated/java/com/influxdb/client/domain/CloudUserLinks.java
  client/src/generated/java/com/influxdb/client/domain/CloudUsers.java
  client/src/generated/java/com/influxdb/client/domain/DBRP.java
  client/src/generated/java/com/influxdb/client/domain/DashboardLinks.java
  client/src/generated/java/com/influxdb/client/domain/Invite.java
  client/src/generated/java/com/influxdb/client/domain/InviteLinks.java
  client/src/generated/java/com/influxdb/client/domain/Invites.java
  client/src/generated/java/com/influxdb/client/domain/InvitesLinks.java
  client/src/generated/java/com/influxdb/client/domain/OperationLog.java
  client/src/generated/java/com/influxdb/client/domain/OperationLogs.java
  client/src/generated/java/com/influxdb/client/domain/OrganizationLinks.java
  client/src/generated/java/com/influxdb/client/domain/Query.java
  client/src/generated/java/com/influxdb/client/domain/ResourceMembers.java
  client/src/generated/java/com/influxdb/client/domain/ResourceOwners.java
  client/src/generated/java/com/influxdb/client/domain/RunLinks.java
  client/src/generated/java/com/influxdb/client/domain/Sources.java
  client/src/generated/java/com/influxdb/client/domain/UserLinks.java
  client/src/generated/java/com/influxdb/client/domain/Users.java
  client/src/generated/java/com/influxdb/client/domain/UsersLinks.java
  client/src/generated/java/com/influxdb/client/service/BucketsService.java
  client/src/generated/java/com/influxdb/client/service/CloudUsersService.java
  client/src/generated/java/com/influxdb/client/service/DashboardsService.java
  client/src/generated/java/com/influxdb/client/service/DbrPsService.java
  client/src/generated/java/com/influxdb/client/service/InvitesService.java
  client/src/generated/java/com/influxdb/client/service/OperationLogsService.java
  client/src/generated/java/com/influxdb/client/service/OrganizationsService.java
  client/src/generated/java/com/influxdb/client/service/SetupService.java
  client/src/generated/java/com/influxdb/client/service/UsersService.java
  client/src/main/java/com/influxdb/client/BucketsApi.java
  client/src/main/java/com/influxdb/client/DashboardsApi.java
  client/src/main/java/com/influxdb/client/OrganizationsApi.java
  client/src/main/java/com/influxdb/client/UsersApi.java
  client/src/main/java/com/influxdb/client/internal/BucketsApiImpl.java
  client/src/main/java/com/influxdb/client/internal/DashboardsApiImpl.java
  client/src/main/java/com/influxdb/client/internal/OrganizationsApiImpl.java
  client/src/main/java/com/influxdb/client/internal/UsersApiImpl.java
  client/src/main/resources/swagger.yml
  client/src/test/java/com/influxdb/client/ITBucketsApi.java
  client/src/test/java/com/influxdb/client/ITDashboardsApi.java
  client/src/test/java/com/influxdb/client/ITDeleteApi.java
  client/src/test/java/com/influxdb/client/ITOrganizationsApi.java
  client/src/test/java/com/influxdb/client/ITTasksApi.java
  client/src/test/java/com/influxdb/client/ITUsersApi.java
  client/src/test/java/com/influxdb/client/InfluxDBClientTest.java
Labels: api

#123 chore(ci): upgrade InfluxDB 1.7 to 1.8 (#104)
  CHANGELOG.md
  scripts/influxdb-restart.sh
Labels: ci

#124 feat: update dependencies & plugins
  CHANGELOG.md
  client-kotlin/pom.xml
  client-scala/pom.xml
  examples/pom.xml
  pom.xml
  scripts/maven-version-rules.xml
  spring/pom.xml
Labels: dependency

#129 fix: serialization of `\n`, `\r` and `\t` to Line Protocol, `=` is valid sign for measurement name
  CHANGELOG.md
  client/src/main/java/com/influxdb/client/write/Point.java
  client/src/test/java/com/influxdb/client/internal/MeasurementMapperTest.java
  client/src/test/java/com/influxdb/client/write/PointTest.java
Labels: bug
